from enum import Enum
class ResponseSignal(Enum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_TOO_LARGE = "FILE_SIZE_TOO_LARGE"
    FILE_UPLOADED_SUCCESS = "FILE_UPLOADED_SUCCESS"
    FILE_UPLOADED_FAILURE = "FILE_UPLOADED_FAILURE"
